### ISSUE TITLE
context per query

### ISSUE THREAD

**Issue by wzrdzl** [PCreations/apollo-link-webworker#1]
Is it possible to pass a new context per query? E.g. I use `user_id` in my context, so I don't want to initialize the `context` only once, I want to be sure that if user has logged out, I don't pass their `user_id` to the `context` anymore

**Comment by PCreations** [comment]
You can do this by composing your link with an instance of [`apollo-link-set-context`](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-set-context). Check out in the Firechat project example the client instanciation : https://github.com/PCreations/firechat/blob/master/src/client.js

**Comment by wzrdzl** [comment]
Cool, I think we can close this one then
